name: Build org modrepo

on:
  # run once per day or manually
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-modrepo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build and publish modrepo.xml from multiple repos
        uses: StationeersLaunchPad/modrepo-builder-action@v1

        with:
          debug-output: "false"
          commit-message: "Update modrepo.xml (automated)"
          mod-repos: |
            aproposmath/stationeers-pytrapic
            aproposmath/StationeersIC10Editor
